---
title: "STAA 566 HW1"
author: "Ruth Hilton"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html')) })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(ggplot2)
library(ggthemes)
library(viridis)
data <- read.csv('student-mat.csv') #Data set about achievement of students in three grading periods on a scale of 0 to 20 over the course of one year
data$G3[data$G3 == 0] <- NA
data
```

```{r}
p_math <- ggplot(data = data, mapping = aes(x = G1, y = G3, color=sex)) + #created mapping 
  geom_smooth(method = "loess", alpha = 0.5) + #add layer with lines
  geom_point(shape = 16) + #add layer with points
  theme_stata(base_size = 10) + #add theme and base font size
  ylab("End of School Year Grade in Mathematics") +
  xlab("Start of School Year Grade in Mathematics (0-20 scale)") +
  guides(color=guide_legend(title="Gender")) +
  theme(legend.position = c(0.87, 0.25)) +
  scale_color_colorblind()
  ggtitle("Growth in Mathematics Grades over One School Year by Gender")
p_math
```

**Citation:**
*P. Cortez and A. Silva. Using Data Mining to Predict Secondary School Student Performance. In A. Brito and J. Teixeira Eds., Proceedings of 5th FUture BUsiness TEChnology Conference (FUBUTEC 2008) pp. 5-12, Porto, Portugal, April, 2008, EUROSIS, ISBN 978-9077381-39-7.* 
